version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_SUPABASE_STORAGE_BUCKET: ${VITE_SUPABASE_STORAGE_BUCKET}
    ports:
      - "80:80"

  ai-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
